using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Constants
{
    public static string opcode_intro = "10";

    static string[] funny_names = { 
    "Bubbles McSnort",
    "Wiggly McPants",
    "Fizzlebottom Puddlejumper",
    "Sir Noodlehead",
    "Captain Quackmire",
    "Professor Wobblepants",
    "Dr. Fizzyboots",
    "Princess Tickleton",
    "Count Gigglesworth",
    "Baron von Burpington",
    "Sir Wobblebottom",
    "Lady Snickerdoodle",
    "Mr. Whiskersnort",
    "Lady Fluffernutter",
    "General Snickerdoodle",
    "Lord Ticklefeather",
    "Squire Jibberjazz",
    "Mayor Gigglesnort",
    "Sir Wobbleberry",
    "Lady Gigglesocks",
    "Sir Wobblewump",
    "Duchess Giggletwist",
    "Baron Tickletoes",
    "Princess Wobblekins",
    "Marquis Snickerpants",
    "Lady Dizzyfeet",
    "Count Snortleberry",
    "Sergeant Fluffybuns",
    "Duke Chuckleberry",
    "Madame Gigglesworth",
    "Admiral Tickletush",
    "Sir Guffawington",
    "Lord Wigglesnort",
    "Colonel Quibblepaws",
    "Lady Tittertwirl",
    "Major Chucklefuzz",
    "Princess Gigglesniff",
    "Baroness Chortlesnort",
    "Sir Wobblewhisk",
    "Lady Wigglesocks",
    "Captain Ticklepuff",
    "Professor Wobblewhistle",
    "Countess Snickersnoot",
    "Squire Guffawtwirl",
    "General Chucklebritches",
    "Duchess Giggledance",
    "Baron Chucklesnicker",
    "Princess Wobblegiggle",
    "Marquis Guffawtwist",
    "Lady Snickersnort",
    "Sergeant Wigglesocks",
    "Duke Fizzlenose",
    "Madame Gigglebritches",
    "Admiral Chucklenoodle",
    "Sir Tittertwist",
    "Lord Wobblepaws",
    "Colonel Snickerfuzz",
    "Lady Titterpuff",
    "Major Wobblewhisk",
    "Princess Gigglecheeks",
    "Baroness Chortleberry",
    "Sir Guffawgiggle",
    "Lady Wobblewhistle",
    "Captain Snickersnoot",
    "Professor Tittertoes",
    "Count Wigglesnicker",
    "Squire Fizzledance",
    "General Gigglesocks",
    "Duchess Chuckletwist",
    "Baron Fizzlefeather",
    "Princess Snortlebritches",
    "Marquis Chucklepaws",
    "Lady Guffawdance",
    "Sergeant Titterwhisk",
    "Duke Wobblegiggle",
    "Madame Giggletoes",
    "Admiral Snickerpuff",
    "Sir Wobblebritches",
    "Lord Fizzlenoodle",
    "Colonel Giggletwirl",
    "Lady Chucklewhisk",
    "Major Snickersnoot",
    "Princess Wigglesnicker",
    "Baroness Fizzledance",
    "Sir Chortlebritches",
    "Lady Guffawgiggle",
    "Captain Wobblewhistle",
    "Professor Snickersnoot",
    "Count Tittertoes",
    "Squire Wigglesnicker",
    "General Fizzledance",
    "Duchess Gigglesocks",
    "Baron Chucklewhisk",
    "Princess Snortlebritches",
    "Marquis Guffawdance",
    "Lady Titterwhisk",
    "Sergeant Wobblegiggle",
    "Duke Giggletoes",
    "Madame Gigglepaws",
    "Admiral Chucklepuff",
    "Sir Fizzlebritches",
    "Lord Snortlenoodle",
    "Colonel Giggletwirl",
    "Lady Chucklesnoot",
    "Major Wigglesnicker"
  };


    public static string GetRandomName() {
        return funny_names[Random.Range(0, funny_names.Length)];
    }
}
